---
title: "Francis I. Proctor Foundation <br> Study Design and Analysis Advisory Services for Faculty in the UCSF Department of Ophthalmology"
---


<br><br>

# Introduction

Welcome to the Francis I. Proctor Foundation design and analysis advisory service page!  The Proctor Foundation has a number of faculty with expertise in epidemiology and biostatistics. As a service to other faculty in the Department of Ophthalmology, Proctor Foundation faculty are available to help advise and assist with research design and statistical analysis. 

<br>

# Guidelines {#guidelines}

We are happy to provide advisory and consulting services to faculty in the Department of Ophthalmology. **Please note that at this time we are only able to accommodate one request per attending faculty member at a time due to limited resources.**

Most request for advisory services fall into the following categories.  Please be prepared to share the following information with us before our first meeting!

<br>

### Study Design or Analysis Advice

* Topic Background
* Research question and specific hypotheses
* Summary of your query for advice
    
### Sample Size & Power Calculations

* Topic Background
* Research question and specific hypotheses
* Planned study design (RCT, cohort, case-control, etc.)
* Clinically relevant effect size/estimate of means in two groups (effect size you want to be able to detect)
* Outcome standard deviation (for continuous outcomes)
* Rate or prevalence of the outcome (for binary outcomes)

### Data Analysis

* Topic Background
* Research question and specific hypotheses
* Summary of the study design
* Vision that you have for results presentation (tables, figures)
* Overview of data source, including type of outcome (binary, categorical, continuous)
* Have your data properly formatted in comma separated values format (.csv). We unfortunately do not have the bandwidth to do data cleaning or extensive data processing. We will let you know if there appear to be obvious errors in the data. Elements of a properly formatted dataset:
  1. de-identified (no patient information!)
  2. variable names are short (3-15 characters) and have no spaces in them (use `x_x` format instead)
  3. data have no completely empty rows
  4. missing values have a clear nomenclature or delineation, e.g. `NA`
  5. categorical variables (factors) have clear labels
  6. dates are in a regular format that is machine-readable
  7. no information is embedded with formatting (italics, highlight, etc.), which is possible in Excel but not possible for .csv or a modern data science work flow
  8. data has a clear structure, with a well-defined unit of observation (repeated observations are OK, so long as they are clearly identified with ID variables)
  9. if multiple datasets/tables exist, they can be clearly [joined by a key variable](https://r4ds.had.co.nz/relational-data.html) in a 1:1 or 1:many relationship.

    

### General guidelines: strive for good scientific & statistical practices!

* Finalize an analysis plan before the analyses are run
* Avoid HARKing (hypothesizing after results are known)
* No _P_-hacking – please don’t ask for models to be run in a different way to try to get _P_<0.05 or _P_<0.005
* Avoid multiple comparisons — minimize the number of models run
* The database will be closed once analysis has started. Make sure your database is final — no new patients, variables, etc. Adding or subtracting patients and re-analyzing is a form of multiple comparisons and will delay the analysis.

<br>

# Plan Ahead, Setting Expectations

Proctor faculty who provide research advisory services are as busy as you are!  They are PIs of their own research groups and often have busy travel schedules. We will do our best to respond within one week of your request to set up an initial meeting.  

Proctor faculty travel often and may not be able to accommodate last-minute requests. Rule of thumb: if you know there is a conference coming up, schedule your consult 6 weeks prior to the submission due date. Anticipate that it could take several weeks to schedule an initial appointment, and several more weeks for an analysis to be complete.

There are more than 50 faculty in the department, many of whom seek advice and help through this service. If you are a "frequent flier" then occasionally we may need to move you down in the queue if other faculty have requested advice for the first time in a 12 month period.

We will always try to be transparent about how much time a project will take, and whether we need to adjust a project’s timeline. 

Below is a summary of the typical amount of time that different types of requests require. Every project is different, but this is based on our overall experience over many years. We strive to have at least one member of our faculty devote ~1 day per week to this work, so an advisory consult will typically have a quick turn-around (i.e., ~1 week), but a data analysis project can require multiple months to complete, depending on the queue of requests.

Type of Service | Proctor Faculty Time Required  | Typical time required from initial request to first round of review  |
:-------------------|:-------|:----------------|
Analysis Advice | 2-3 hours | 1-2 weeks |
Study Design Advice | 2-3 hours | 1-2 weeks |
Study Sample Size | 2-4 hours | 1-2 weeks |
Help with a small data analysis (e.g., one regression, one figure) | 0.5 -1 day | 1-3 weeks * |
Help with a data analysis for an entire paper | 3-5 days | 4-8 weeks * |

Proctor faculty have extensive experience in many areas of epidemiology and biostatistics. If your question falls outside our areas of expertise, or if you need an analysis completed on a timeline that we cannot accommodate, we will do our best to point you towards the right resources. UCSF has a campus-wide biostatistics consulting service available as well: https://consult.ucsf.edu/biostatistics 


<br>

# Make an Appointment

If you would like to discuss your research project with us, please complete this Qualtrics form!  

https://ucsf.co1.qualtrics.com/jfe/form/SV_9WXVQpCw4s9sq0t 

We use this to manage the queue. We will schedule an initial 30-minute meeting. Please come prepared (see [Guidelines](#guidelines), above). 

If you have not received a response within 1 week of submitting the form then please email Dr. Ben Arnold (ben.arnold@ucsf.edu), who is head of Proctor’s Data Coordinating Center and currently coordinates the design and analysis advisory services to the department. 


